version: "3.2"
services:
  apiserver:
    build:
      dockerfile: Dockerfile
      context: .
    command:
      - "uvicorn"
      - "src.app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - "config/.env"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
