version: "3.2"
services:
  worker:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ".env"
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
